### ISSUE TITLE
Not working on RPI0 with Waveshare 2.13Inch E-Ink

### ISSUE THREAD

**Issue by Shaun-Harrison** [DurandA/inky-cryptochart#3]
Hello

My new waveshare e-ink turned up today, and just to warn you I am very new to this and python in general

I've setup the e-ink and ran some examples so I know the e-ink is up and running
I've cloned your repo, installed the pre-req's and the required pip3 packages

I couldn't find `inky212x104` module anywhere to change the pins like the readme states, so I installed inky-phat  via `apt-get install python3-inkyphat` and then edited `/usr/lib/python3/dist-packages/inkyphat/inky212x104.py` to change the pins as per the instructions

I'm now able to run the `cryptochart.py` script, which runs and finishes, but nothing is displayed on the screen

**Comment by DurandA** [comment]
Hello @Shaun-Harrison (one year later)!

I updated the software to easily switch between display drivers. Let me know if you have any issue with your display.
